env:
  node: true
  es6: true
  jest: true
extends:
  - google
  - 'plugin:@typescript-eslint/recommended'
  - prettier
  - plugin:import/recommended
  - plugin:import/typescript

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
settings:
  import/resolver:
    typescript: {}
    node:
      paths:
        - 'src'
plugins:
  - prettier
  - import
rules:
  {
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/explicit-member-accessibility': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    require-jsdoc: 'off',
    new-cap: 'off',
    prettier/prettier: 'error',
    import/no-cycle: ['warn', { maxDepth: 5 }],
  }
