env:
  es6: true
  node: true
extends:
  - google
  - 'plugin:@typescript-eslint/recommended'
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - prettier
  - '@typescript-eslint'
rules:
  {
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/explicit-member-accessibility': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    require-jsdoc: 'off',
    new-cap: 'off',
  }
