service: licoreriaryc-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment: ${self:custom.${self:provider.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:GetObject
        - s3:GetObjectAcl
      Resource: 'arn:aws:s3:::${provider.environment.BUCKET}/*'
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}'

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  bucket: ${self:service}-${self:provider.stage}
  dev:
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
    BUCKET: ${self:custom.bucket}
  prod:
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
    BUCKET: ${self:custom.bucket}
  serverless-offline:
    port: 4000
  webpackIncludeModules: true
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true

functions:
  graphql:
    handler: src/handler.default
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
